# forms the design and layout of generate screen
<GenerateScreen>:
	Widget:
		canvas:
			Color:
				rgba: rgba('#07575B')
			Rectangle:
				size: self.size
				pos: self.pos
    FloatLayout:
		pos_hint: {'center_y': 0.65, 'center_x': 0.5}
		size_hint: 8, 0.6
		FloatLayout:
			pos_hint: {'center_y': 0.5, 'center_x': 0.5}
			size_hint: 8, 0.7
			Image:
				pos_hint: {'center_x': 0.5, 'center_y' : 0.5}
				source: 'Media/Front_Image.png'
				size_hint_x: 1
				allow_stretch: False
		FloatLayout:
			pos_hint: {'center_y': 0.9, 'center_x': 0.5}
			size_hint: 8, 0.2
			Image:
				pos_hint: {'center_x': 0.5, 'center_y' : 0.5}
				source: 'Media/QR_Attendance_Logo.png'
				size_hint_x: 0.03
				allow_stretch: False
		MDLabel:
            text: ('[font=Fonts/Roboto-Black]Quick Response (QR) Attendance[/font]')
            halign: 'center'
            font_size: '18dp'
            markup: True
			halign: "center"
			theme_text_color: 'Custom'
            text_color: rgba('#C0DEE5')
            pos_hint: {'center_x': 0.5, 'center_y' : 0.08}
    FloatLayout:
		pos_hint: {'center_y': 0.2, 'center_x': 1.1}
		size_hint: 0.4, 0.7
        canvas:
            Color:
                rgba: rgba('#C0DEE5')
            Ellipse:
                pos: self.pos
                size: self.size
    FloatLayout:
		pos_hint: {'center_y': 0.02, 'center_x': 0.9}
		size_hint: 0.6, 0.7
        canvas:
            Color:
                rgba: rgba('#C0DEE5')
            Ellipse:
                pos: self.pos
                size: self.size
    FloatLayout:
		pos_hint: {'center_y': 1.1, 'center_x': 0.001}
		size_hint: 0.4, 0.7
        canvas:
            Color:
                rgba: rgba('#C0DEE5')
            Ellipse:
                pos: self.pos
                size: self.size
    FloatLayout:
		pos_hint: {'center_y': 1.25, 'center_x': 0.15}
		size_hint: 0.6, 0.7
        canvas:
            Color:
                rgba: rgba('#C0DEE5')
            Ellipse:
                pos: self.pos
                size: self.size
    FloatLayout:
		pos_hint: {'center_y': 0.15, 'center_x': 0.5}
		size_hint: 1, 0.3
        canvas:
            Color:
                rgba: rgba('#C0DEE5')
            Rectangle:
                pos: self.pos
                size: self.size
		MDFillRoundFlatButton:
			text: '[font=Fonts/Roboto-Bold][color=#FFFFFF]        Generate QR Code        [/color][/font]'
			markup: True
			md_bg_color: rgba('#07575B')
            font_size: "15dp"
			pos_hint: {'center_x' : 0.5, 'center_y' : 0.65}
			on_press:
                root.manager.transition.direction = 'right'
                root.manager.transition.duration = .3
                root.check_information()
		MDTextButton:
			text: '[font=Fonts/Roboto-Bold]Edit Your Information[/font]'
			markup: True
			color: rgba('#07575B')
            font_size: "15dp"
			pos_hint: {'center_x' : 0.5, 'center_y' : 0.4}
			on_press:
                root.manager.transition.direction = 'right'
                root.manager.transition.duration = .3
                root.manager.current = 'information'
		MDIconButton:
			icon: "information-outline"
			user_font_size: "20sp"
			theme_text_color: "Custom"
			text_color: rgba('#07575B')
			pos_hint: {'center_x' : 0.9, 'center_y' : 0.2}
			on_press:
                root.manager.transition.direction = 'right'
                root.manager.transition.duration = .3
                root.manager.current = 'help'
