<HelpScreen>
	Widget:
		canvas:
			Color:
				rgba: rgba('#C0DEE5')
			Rectangle:
				size: self.size
				pos: self.pos
    FloatLayout:
		pos_hint: {'center_y': 0.65, 'center_x': 0.5}
		size_hint: 8, 0.6
		FloatLayout:
			pos_hint: {'center_y': 0.9, 'center_x': 0.5}
			size_hint: 8, 0.2
			Image:
				pos_hint: {'center_x': 0.5, 'center_y' : 0.5}
				source: 'Media/QR_Attendance_Logo.png'
				size_hint_x: 0.04
				allow_stretch: False
	FloatLayout:
		pos_hint: {'center_y': 0.4, 'center_x': 0.5}
		size_hint: 1, 0.8
		canvas:
			Color:
				rgba: rgba('#07575B')
			RoundedRectangle:
				radius: [40,40,0,0]
				size: self.size
				pos: self.pos
		MDLabel:
            text: ('[font=Fonts/Roboto-Black]Help[/font]')
            halign: 'center'
            font_size: '20dp'
            markup: True
			halign: "center"
			theme_text_color: 'Custom'
            text_color: rgba('#C0DEE5')
            pos_hint: {'center_x': 0.5, 'center_y' : 0.93}
	MDIconButton:
		icon: "arrow-left-bold-circle"
		user_font_size: "25sp"
		theme_text_color: "Custom"
		text_color: rgba('#07575B')
		pos_hint: {'center_x' : 0.1, 'center_y' : 0.95}
		on_press:
			root.manager.current = "generate"
			root.manager.transition.direction = "left"
			root.manager.transition.duration = .3
