<InformationScreen>
	Widget:
		canvas:
			Color:
				rgba: rgba('#C0DEE5')
			Rectangle:
				size: self.size
				pos: self.pos
    FloatLayout:
		pos_hint: {'center_y': 0.65, 'center_x': 0.5}
		size_hint: 8, 0.6
		FloatLayout:
			pos_hint: {'center_y': 0.9, 'center_x': 0.5}
			size_hint: 8, 0.2
			Image:
				pos_hint: {'center_x': 0.5, 'center_y' : 0.5}
				source: 'Media/QR_Attendance_Logo.png'
				size_hint_x: 0.04
				allow_stretch: False
	FloatLayout:
		pos_hint: {'center_y': 0.4, 'center_x': 0.5}
		size_hint: 1, 0.8
		canvas:
			Color:
				rgba: rgba('#07575B')
			RoundedRectangle:
				radius: [40,40,0,0]
				size: self.size
				pos: self.pos
		MDLabel:
            text: ('[font=Fonts/Roboto-Black]Your Information[/font]')
            halign: 'center'
            font_size: '20dp'
            markup: True
			halign: "center"
			theme_text_color: 'Custom'
            text_color: rgba('#C0DEE5')
            pos_hint: {'center_x': 0.5, 'center_y' : 0.93}
		MDLabel:
            text: ('[font=Fonts/Roboto-Black]Full Name[/font]')
            halign: 'left'
            font_size: '10dp'
            markup: True
			theme_text_color: 'Custom'
            text_color: rgba('#C0DEE5')
            pos_hint: {'center_x': 0.6, 'center_y' : 0.77}
		MDTextFieldRound:
			id: full_name
			hint_text: 'Enter Your Full Name Here'
			text_color: rgba('#C0DEE5')
			size_hint: (0.75, None)
            font_size: "10dp"
			pos_hint: {'center_x' : 0.5, 'center_y' : 0.71}
			normal_color: rgba('#FFFFFF')
			color_active: rgba('#C0DEE5')
			line_color: rgba('#C0DEE5')
		MDLabel:
            text: ('[font=Fonts/Roboto-Black]Course and Section[/font]')
            halign: 'left'
            font_size: '10dp'
            markup: True
			theme_text_color: 'Custom'
            text_color: rgba('#C0DEE5')
            pos_hint: {'center_x': 0.6, 'center_y' : 0.63}
		MDTextFieldRound:
			id: course_section
			hint_text: 'Enter Your Course and Section Here'
			text_color: rgba('#C0DEE5')
			size_hint: (0.75, None)
            font_size: "10dp"
			pos_hint: {'center_x' : 0.5, 'center_y' : 0.57}
			normal_color: rgba('#FFFFFF')
			color_active: rgba('#C0DEE5')
			line_color: rgba('#C0DEE5')
		MDLabel:
            text: ('[font=Fonts/Roboto-Black]Student Number[/font]')
            halign: 'left'
            font_size: '10dp'
            markup: True
			theme_text_color: 'Custom'
            text_color: rgba('#C0DEE5')
            pos_hint: {'center_x': 0.6, 'center_y' : 0.49}
		MDTextFieldRound:
			id: student_number
			hint_text: 'Enter Your Student Number Here'
			text_color: rgba('#C0DEE5')
			size_hint: (0.75, None)
            font_size: "10dp"
			pos_hint: {'center_x' : 0.5, 'center_y' : 0.43}
			normal_color: rgba('#FFFFFF')
			color_active: rgba('#C0DEE5')
			line_color: rgba('#C0DEE5')
		MDLabel:
            text: ('[font=Fonts/Roboto-Black]Contact Number[/font]')
            halign: 'left'
            font_size: '10dp'
            markup: True
			theme_text_color: 'Custom'
            text_color: rgba('#C0DEE5')
            pos_hint: {'center_x': 0.6, 'center_y' : 0.35}
		MDTextFieldRound:
			id: contact_number
			hint_text: 'Enter Your Contact Number Here'
			text_color: rgba('#C0DEE5')
			size_hint: (0.75, None)
            font_size: "10dp"
			pos_hint: {'center_x' : 0.5, 'center_y' : 0.29}
			normal_color: rgba('#FFFFFF')
			color_active: rgba('#C0DEE5')
			line_color: rgba('#C0DEE5')
		MDFillRoundFlatButton:
			text: '[font=Fonts/Roboto-Bold][color=#07575B]        Update Your Info        [/color][/font]'
			markup: True
			md_bg_color: rgba('#C0DEE5')
            font_size: "15dp"
			pos_hint: {'center_x' : 0.5, 'center_y' : 0.1}
			on_press:
                root.manager.transition.direction = 'right'
                root.manager.transition.duration = .3
                root.manager.current = '#'
	MDIconButton:
		icon: "arrow-left-bold-circle"
		user_font_size: "25sp"
		theme_text_color: "Custom"
		text_color: rgba('#07575B')
		pos_hint: {'center_x' : 0.1, 'center_y' : 0.95}
		on_press:
			root.manager.current = "generate"
			root.manager.transition.direction = "left"
			root.manager.transition.duration = .3
